const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})



async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `
    You are an interview preparation assistant.

    Analyze the candidate profile and job description and generate a detailed interview report.

    Candidate Resume:
    ${resume}

    Candidate Self Description:
    ${selfDescription}

    Target Job Description:
    ${jobDescription}

    Generate a JSON response EXACTLY matching this structure:
    {
      "title": "Job Role Title",
      "matchScore": 85,
      "technicalQuestions": [
        { "question": "Question text...", "intention": "Why ask this...", "answer": "How to answer..." }
      ],
      "behavioralQuestions": [
        { "question": "Question text...", "intention": "Why ask this...", "answer": "How to answer..." }
      ],
      "skillGaps": [
        { "skill": "Skill name", "severity": "low" | "medium" | "high" }
      ],
      "preparationPlan": [
        { "day": 1, "focus": "Topic focus", "tasks": ["Task 1", "Task 2"] }
      ]
    }

    Return ONLY JSON. No extra text.
    `

    const response = await ai.models.generateContent({
        model: "gemini-1.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json"
        }
    })
    console.log("RAW AI RESPONSE:", response.text) 
    

    const rawText = response.text;

    const start = rawText.indexOf("{");
    const end = rawText.lastIndexOf("}");

    const jsonString = rawText.slice(start, end + 1);

    const data = JSON.parse(jsonString);

    console.log("AI DATA:", data);

    return data;
}



async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-1.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })


    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }